### ISSUE TITLE
-getinfo

### ISSUE THREAD

**Issue by chronzz** [ilsawa/p2pool-lcc#2]
after starting the pool i get -getinfo depreciated how do i fix this

**Comment by chronzz** [comment]
fixed getinfo but now i get 

`Fatal error:
Traceback (most recent call last):
  File "/home/p2p/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/home/p2p/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/p2p/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
  File "/home/p2p/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
--- <exception caught here> ---
  File "/home/p2p/p2pool-lcc/p2pool/main.py", line 148, in main
    my_pubkey_hash = bitcoin_data.address_to_pubkey_hash(address, net.PARENT)
  File "/home/p2p/p2pool-lcc/p2pool/bitcoin/data.py", line 329, in address_to_pubkey_hash
    raise ValueError('address not for this net!')
exceptions.ValueError: address not for this net!
`

**Comment by farsider350** [comment]
If LCC is able to generate a Legacy address then this will help

Go to Core wallet Console and type
getnewaddress "" legacy
copy the new address into p2pool/data/litecoincash/cached_payout_address

**Comment by chronzz** [comment]
thank you so much that worked :)
